version: "3"
services:
  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - image_search_api
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  image_search_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - 8080
    restart: always
    tty: true
    command: "image_search_api run-uwsgi"
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.update-cache.schedule: "@every 60m"
      ofelia.job-exec.update-cache.command: "curl -X GET 'http://localhost:8080/api/v1.0/cache/update_cache' -H 'accept: application/json'"
